"""empty message

Revision ID: 6d5f816495f8
Revises: d46ffdeb0855
Create Date: 2016-10-14 12:01:23.001673

"""

# revision identifiers, used by Alembic.
revision = '6d5f816495f8'
down_revision = 'd46ffdeb0855'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('todos', 'updated_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('updated_time', sa.INTEGER(), nullable=True))
    op.drop_column('todos', 'user_id')
    ### end Alembic commands ###
